services:
  frontend:
    image: daily-kindness-frontend
    container_name: daily-kindness-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND=http://localhost:5000 
    ports:
      - 8080:80